### ISSUE TITLE
support for OS X

### ISSUE THREAD

**Issue by elaforge** [TravisWhitaker/cpuinfo#1]
Hi, I need a module with physical cpus for both Linux and OS X, and I thought of adding it to cpuinfo, but I think the current API isn't going to work for anything other than linux.  The reason is the CPU type has a million fields, many of them are linux-specific, and the useful functions like `physicalCores` require CPUs.

What I would do is change functions like physicalCores to have type `IO Int`.  This is implemented as `/usr/sbin/sysctl -n hw.physicalcpu` on OS X, and by parsing /proc/cpuinfo on linux.  If they all throw the same NotSupported exception, we can have a `try` which turns them into `Maybe Int` if you don't want to crash on an unsupported platform.

Personally I'd just get rid of the CPU type because I don't have a use for all those fields, but I guess it doesn't hurt to have it, as long as it's clear that it's Linux-specific.  Even use CPP to make it not compile on non-linux instead of compile but crash at runtime, but I don't care much either way.

Would you be interested in a change like that?  It would be basically a rewrite and incompatible API.  Otherwise I can make my own package easily enough, but it's a bit of a shame to have two similar packages in hackage.  You could also transfer ownership to me if you'd like.

**Comment by TravisWhitaker** [comment]
It looks to me like `systectl -a` on macOS actually provides most of the fields in the `CPU` type already. In fact, it looks like it provides a lot of potentially useful information that's missing from `/proc/cpuinfo` on Linux, like information about the cache topology.

I'll admit that the fields included in the type were chosen based on the information readily available in `/proc/cpuinfo`, but the only field that is Linux-specific is `bogoMIPS` (which should be a `Maybe Double`, seems it was a mistake I made a while ago). The rest of the fields are properties of the CPU and microcode, although the names they go by and how they're found out at runtime differ among OSs.

As far as this package's API is concerned, it'd be nice if it were the same across platforms. And as far as macOS is concerned, I think we should use the `sys/sysctl.h` API (as the Apple-specific functionality here does: https://opensource.apple.com/source/system_cmds/system_cmds-671.10.3/sysctl.tproj/sysctl.c) rather than forking a process. It's unfortunate that the same API doesn't provide similar information on Linux...

**Comment by elaforge** [comment]
Yeah, for sure the API should be the same, that's why I suggested individual functions instead of a record with everything, that way you only depend on what you need.  Also because I lazily only want to implement what I know is needed, not every possible thing that anyone might theoretically need.  Surely if you need that level of depth, you will write your own hardware querying stuff, not use some generic library.

I'll see if it's easy to get things out of sysctl(3) and how easy it is to populate CPU.  sysctlbyname seems not too bad actually.  But if you're worried about the overhead of a fork, why not the overhead of calling sysctlbyname for every field when you only want one of them?

**Comment by TravisWhitaker** [comment]
> Surely if you need that level of depth, you will write your own hardware querying stuff, not use some generic library.

Getting physical CPU details is what I made this library for. If one doesn't need these details, it's much easier to run with `+RTS -N`, use `getNumCapabilites` and, if necessary, divide by two.

> But if you're worried about the overhead of a fork, why not the overhead of calling sysctlbyname for every field when you only want one of them?

It's not about the overhead of a fork. It's about choosing between a dependency on the string output of a command line tool and a C API.

**Comment by elaforge** [comment]
Sorry about the delay.  I wound up just using sysctl.  I just need physical cores and realized that trying to implement a general purpose thing was overkill.
